ALTER TABLE public.pre_cadastros 
ADD COLUMN IF NOT EXISTS cpf_valido BOOLEAN,
ADD COLUMN IF NOT EXISTS cnpj_valido BOOLEAN,
ADD COLUMN IF NOT EXISTS nivel_risco TEXT,
ADD COLUMN IF NOT EXISTS idade INTEGER,
ADD COLUMN IF NOT EXISTS documentacao_completa BOOLEAN,
ADD COLUMN IF NOT EXISTS dados_consistentes BOOLEAN,
ADD COLUMN IF NOT EXISTS data_validacao TIMESTAMPTZ;
